# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca87191e648399e68315d051730b364370433939cdc1e2253e6a42024fb4d24a06a479528cbf0cd1854444118941df98432ce476cfe959a7fa06e15162e03ff1

test:
  secret_key_base: 182abf42d5a4bbf413ab9334ca1ce1da5d784ef70e132f25632f28d2ca63c1fb90624d7683a9f43b0a74a99b1fc63f28428b93d470c1cf477fe91a44981a619e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
